version: "3"
services:
  database:
    image: mariadb:10.0-xenial
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306 # expose port for development purposes
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  backend:
    depends_on: 
      - database
    build: ./backend
  frontend:
    depends_on: 
      - backend
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

