version: "3"
services:
  database:
    image: mariadb:10.4
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306 # expose port for development purposes
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  app:
    ports:
      - 80:8080 # expose port for development purposes
    depends_on: 
      - database
    build: ./app

